# Generated by Django 5.0.6 on 2024-06-23 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startingnode', models.CharField(max_length=100)),
                ('isdirected', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('txt', models.FileField(upload_to='graph/txt/')),
            ],
        ),
        migrations.DeleteModel(
            name='GraphStartNode',
        ),
    ]
