# Generated by Django 5.0.6 on 2024-06-27 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomePage', '0003_remove_graphmodel_isdirected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphmodel',
            name='txt',
        ),
        migrations.AddField(
            model_name='graphmodel',
            name='graph',
            field=models.FileField(default=1, upload_to='graph/upload/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
            preserve_default=False,
        ),
    ]
